### ISSUE TITLE
Create a public git repository for your project (Mike)

### ISSUE THREAD

**Issue by media1mogul** [thisaintwork/AgileDungeonTrekking#1]
Create a public git repository for your project and submit the repo URL as the solution to this assignment.

Definition of done includes:

- [x] Create the repository in the thisaintwork organization
- [x]  Invite all team members to the  "thisaintwork" organization
- [x] Make all team owners of the "thisaintwork" organization
- [x] Create a project (in the new projects beta) for sprints
- [x] Create a team in the organization called "The Traveling Players"
- [x] Invite all team members to the team
- [x] Give team access to the AgileDungeonTrekking repo as admin
- [x] Add all the checklist items for the project part one to the ungroomed backlog
- [x] Announce in the team Discord Channel
- [x] Add the repo URL to Kelly's doc

Review & QA
- [x] Confirm everyone belongs to the repository
- [x] Confirm the project and repo are public
- [x] Confirm everyone has access to the repo
- [x] Confirm everyone has access to the associated project.
- [x] Confirm the URL got moved to the repo readme
- [x] Submit the repo URL as the solution to this assignment.
  - After reading the assignment again, I think that this submission signals we're ready to have our repo checked.  I'm not going to submit the repo URL until the readme and anything else like the backlog is done.

**Comment by media1mogul** [comment]
![image](https://user-images.githubusercontent.com/25803174/197402765-ea697096-2667-46fb-acb4-d2335e007bcb.png)

**Comment by mreekie** [comment]
Created Project for dealing with Backlog.
https://github.com/orgs/thisaintwork/projects/1/views/1

- Created it at the organizational level following best practices
  - A project at the org level can pull issues from any repository that it has access to in the organization.
- Invited the team with admin role.
- I don't think we really need a second project for managing the backlog.  We can do everything on one board for this project.
- Added the "usual" columns

I think it's done.

**Comment by mreekie** [comment]
Notes on the setup:
Everything
- lives under the [thisaintwork](https://github.com/thisaintwork) organization

[The Traveling Players](https://github.com/orgs/thisaintwork/teams/traveling-players) group
 - Has admin access to the  [AgileDungeonTrekking repo](https://github.com/thisaintwork/AgileDungeonTrekking/issues)
 - Has admin access to the [AgileDungeonTrekking project ](https://github.com/orgs/thisaintwork/projects/1/views/1)

  - The "The Traveling Players" team has admin access

[AgileDungeonTrekking repo](https://github.com/thisaintwork/AgileDungeonTrekking/issues)
 - Is public
 - Is populated with all the action items that I know of that came out of the first meeting that I remember.   This gives us a backlog but it's not groomed at all.

**Comment by mreekie** [comment]
Next Step is someone else on the team looks it over and gives it a review.
If it passes review we can post the URL to claim the assignment as done.

**Comment by mreekie** [comment]
Next steps:
- [ ] Confirm access
- [ ] Mike give everyone Ownership privelidges in addition to admin

**Comment by mreekie** [comment]
As examples of how we can use labels:
- I've added a label to [everything associated with our homework](https://github.com/thisaintwork/AgileDungeonTrekking/labels/HW1✔📃).

**Comment by mreekie** [comment]
Still missing drew and Kelly. Will try to get them in tonight.

**Comment by mreekie** [comment]
Kelly is in and confirmed.
I just added drew tonight.
Once he's confirmed I can close this.

**Comment by mreekie** [comment]
Today I updated the readme with the Repo URL.
I submitted the repo URL for the homework assignment.
