### ISSUE TITLE
[4 POINTS] As a user I can see the beautiful background picture on the dashboard page (decomposed from #57)

### ISSUE THREAD

**Issue by mreekie** [thisaintwork/AgileDungeonTrekking#104]
**User Story Title:  Characters and Creatures.**

**Opening & Details:**
As a DM or player, as I go through the process of creating or accessing my account live on the web, I want to have the nice background that I saw during my acceptance of the login.

**Acceptance Criteria:**
- [ ] When I login I see the login page that already exists with no change to the behavior
- [ ] When I login I see the nice background you showed me from the demo.

**Story Points Estimate:**
4

**Definition of Ready**
- [x] User story has a title
- [x] User story opening sentence
- [x] User story additional details
- [x] User story has a clear, complete acceptance criteria
- [x] User story is estimated in story points
- [x] User story addresses a business need
- [x] User story has measurable acceptance criteria
- [x] User story is small enough for implementation in the given time, but large enough to provide customer value

---
**Technical Tasks:**

To get here we need to get past the technical issues we've been having with the production site.  As best we can tell the issues is on our side and is related to having an understanding of how django running live versus local  works.

Here's a rough cut at what needs to get us past the technical issues:
- [x] Work out the issue between pycharm dev and the public site when it comes to displaying the background and other pictures
  - Go back to a very simple sample website that includes the pictures and get it working.
  - setup the infrastructure to support BDD.
  - Demonstrate the result on the simple demo site with BDD
- [x] Move the concepts into the "real" code.
- [x] demonstrate that the user can now see the pictures in production.
- [x] hook up the code and get it to autodeploy upon checkin to main.
- [x] hook our tests into the build process so that it will only deploy to production if our test suite passes
- [ ] Find and fix issues that are triggering build failure 
- [ ] Convert database over to postgress from sqllite
- [ ] confirm that we can still reach the site at www.agiledungeontrekking.online
- [ ] confirm that we can still reach the site at agiledungeontrekking.online

---
Was decomposed from Big Story: 
- #26

**Comment by mreekie** [comment]
How it looks in dev:
![image](https://user-images.githubusercontent.com/47538814/202906670-ce1117a9-9be9-4c4d-bb4c-f78f34fb01e2.png)

**Comment by mreekie** [comment]
Working through the simple website. I recall our site uses mysql, but that production database uses postgress.
I don't know if there is a compatibility issue here or not yet.
There may not be. But for the future me, here are the settings:
https://docs.djangoproject.com/en/4.1/intro/tutorial02/

**Comment by mreekie** [comment]
I've gotten as far as https://docs.djangoproject.com/en/4.1/intro/tutorial03/#namespacing-url-names
There's a lot left to learn but this gets me the basics.
From what I've read thus far the images _might_  be a namespacing problem.
I'm going to go back to our code now and apply what I've learned.

**Comment by media1mogul** [comment]
We assessed the situation and figured out we were trying too hard to do everything ourselves.
Drew got us over to a digital ocean App based solution from the drip.
We got the Continuous deployment almost for free when we did that.
The build tests were also easy to hook in.

**Comment by mreekie** [comment]
We assessed the situation and figured out we were trying too hard to do everything ourselves.
The error in the original setup was a space in the 

Drew  got us over to a digital ocean App based heroku solution from the drip solution.
We got the Continuous deployment almost for free when we did that.
The build tests were also easy to hook in using this method.

**Comment by mreekie** [comment]
Added to zone: agiledungeontrekking.online

Type | key | data | timeout
--- | --- | --- | ---
CNAME | www | king-prawn-app-i5gxu.ondigitalocean.app | 1 hr
CNAME | @| king-prawn-app-i5gxu.ondigitalocean.appn | 1 hr

**Comment by mreekie** [comment]
agiledungeontrekking.online worked the first time though I got warnings about secure connections.

Nslookup works:
C:\Users\perftest>nslookup
Default Server:  dns.google
Address:  8.8.8.8

> www.agiledungeontrekking.online
Server:  dns.google
Address:  8.8.8.8

Non-authoritative answer:
Name:    king-prawn-app-i5gxu.ondigitalocean.app
Addresses:  2606:4700::6810:f34e
          2606:4700::6810:f44e
          209.97.148.138
Aliases:  www.agiledungeontrekking.online

> agiledungeontrekking.online
Server:  dns.google
Address:  8.8.8.8

Non-authoritative answer:
Name:    agiledungeontrekking.online
Address:  209.97.148.138

>

I'm not 100% sure of using cnames versus forwarding.
I'm guessing this is where the issue comes in however.
Digital ocean is proving https service.
So coming in from a different namespace is bad.

**Comment by mreekie** [comment]
Found:
https://aragonalvarez.medium.com/how-to-add-a-custom-domain-to-your-heroku-app-a42cc2af31e7

It's not working so I'm going to adjust what I put in. 
Theirs is pre-pended with "app"

**Comment by mreekie** [comment]
Going back - build is failing on:


![Image](https://user-images.githubusercontent.com/47538814/203657341-5147d14e-5edd-41a7-b2aa-e2ed5b912905.png)

**Comment by mreekie** [comment]
There was a failed push from the repo unrelated to the tests.py failure.
Sounds like not all files were updated.
Will continue after resolution.

Next Steps:
- [ ] Confirm production is back-up
- [ ] Work through the domain addition and SSL certs setup
   - not sure at this point if the 'app' prefix means anything at all or is just a convention.

**Comment by mreekie** [comment]
Second attempt.
- Followed example - used prefix app.

Nslookup works:
perftest@ubuntu:~$ nslookup
> app.agiledungeontrekking.online
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
app.agiledungeontrekking.online	canonical name = king-prawn-app-i5gxu.ondigitalocean.app.
Name:	king-prawn-app-i5gxu.ondigitalocean.app
Address: 104.16.244.78
Name:	king-prawn-app-i5gxu.ondigitalocean.app
Address: 104.16.243.78
Name:	king-prawn-app-i5gxu.ondigitalocean.app
Address: 2606:4700::6810:f34e
Name:	king-prawn-app-i5gxu.ondigitalocean.app
Address: 2606:4700::6810:f44e
> 

Resolution in the browser does not.
The SSL portion of this is automated?
Maybe it takes some time to complete?


Nothing yet on crt.sh
https://crt.sh/?q=app.agiledungeontrekking.online

![Image](https://user-images.githubusercontent.com/47538814/203675949-2275b22e-592a-4088-9909-680573184f59.png)

**Comment by mreekie** [comment]
![Image](https://user-images.githubusercontent.com/47538814/203849654-8048af9f-d02f-4d4e-8239-727caabc28f6.png)

**Comment by mreekie** [comment]
Last thing I'll try before doing a docs deepdive is taking the trailing dot off the cname target.
I'm pretty sure that's something I recollect can be an issue with some DNS editing pages.





![Image](https://user-images.githubusercontent.com/47538814/203853291-212f28d6-4f0f-401a-bafe-c9146da23f31.png)

**Comment by mreekie** [comment]
https://docs.digitalocean.com/products/app-platform/how-to/manage-domains/
Reading more carefully through official docs.
It sounds like I need to insert a CNAME from the domain itself, not a subdomain (e.g. app) back to the app.

- [ ]  Add a CNAME at the domain level in the zone.
- [ ] Add the domain as an additional domain for our app
- [ ] Check crt.sh to see if a certificate was automatically created.

---
I added the top level cname and deleted all the other non-essential zone entries.


![Image](https://user-images.githubusercontent.com/47538814/203858548-6fe08a2a-f194-4085-865f-0cb725360514.png)


nslookup:
> agiledungeontrekking.online
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
agiledungeontrekking.online	canonical name = king-prawn-app-i5gxu.ondigitalocean.app.
Name:	king-prawn-app-i5gxu.ondigitalocean.app
Address: 104.16.243.78
Name:	king-prawn-app-i5gxu.ondigitalocean.app
Address: 104.16.244.78
Name:	king-prawn-app-i5gxu.ondigitalocean.app
Address: 2606:4700::6810:f34e
Name:	king-prawn-app-i5gxu.ondigitalocean.app
Address: 2606:4700::6810:f44e

---



![Image](https://user-images.githubusercontent.com/47538814/203859145-4e44ccec-2811-4401-9f16-f9203841a44d.png)


---



![Image](https://user-images.githubusercontent.com/47538814/203858989-d74fdea1-0f55-4886-a760-058ccca3d10f.png)

**Comment by mreekie** [comment]
https://docs.digitalocean.com/products/app-platform/how-to/manage-domains/
Reading more carefully through official docs.
Lets look at this note - maybe mydomain.com does not support CNAME flattening
Try out using the alternative * domain entry.

- [x]  Add a CNAME at the domain level in the zone.
- [x] Add the * domain as an additional domain for our app
- [PASS] Check crt.sh to see if a certificate was automatically created.
- [FAIL] Check that site responds on our custom domain

![Image](https://user-images.githubusercontent.com/47538814/203859563-003a7a02-2476-47b5-b4e4-2dbcf1271b27.png)
...
![Image](https://user-images.githubusercontent.com/47538814/203859865-6fefc05f-27b8-4b86-9b9a-70de1b5922a8.png)
...
![Image](https://user-images.githubusercontent.com/47538814/203860049-b09bb31e-d133-40c2-a97e-a4607f39a4ac.png)
...
![Image](https://user-images.githubusercontent.com/47538814/203860231-2a3379cf-da45-4f25-9c9d-6eb8058a6540.png)
...
![Image](https://user-images.githubusercontent.com/47538814/203860334-cd876a92-dc7c-45ce-af53-6c36a268e8ba.png)
...


**It never asked me about the TXT records? Why**

**Comment by mreekie** [comment]
The txt record request is there now.


![Image](https://user-images.githubusercontent.com/47538814/203883142-58980c78-8d96-49b1-8e65-1a07d2953c07.png)

**Comment by mreekie** [comment]
This is resolved.
- It's unsatisfying in that the setup is still displaying an error.
![image](https://user-images.githubusercontent.com/47538814/204107284-b2d8467f-8de4-48ee-9477-d1ca2303cc1e.png)

- However, the app is up and running happily on our custom domain.
 - My current operating theory is that I went outside the lines by initiating the auto-certificate process several times, as seen by the report.
![image](https://user-images.githubusercontent.com/47538814/204107338-22ae73c2-f6d1-48c7-9f1c-f48474ee79c2.png)

Here is the app happily running at our URL;
![image](https://user-images.githubusercontent.com/47538814/204107365-41aa114f-87c7-4fce-9e8f-70fe66368eed.png)
