### ISSUE TITLE
Bug: Build tests failing - why?

### ISSUE THREAD

**Issue by mreekie** [thisaintwork/AgileDungeonTrekking#105]
Description:
Build tests are failing.  We don't know why. We need to swarm on this and fix it.

Plan:
- [x] Mike and Drew are going to investigate starting with what we know now and working backwards. 
  - Diana has provided her phone number so we can reach out directly if we find something code related.
- [x] Diana had a test setup to fail in her dev environment as part of the TDD testing.  She will remove this 

![image](https://user-images.githubusercontent.com/47538814/204065416-a1bd3c83-cf94-4949-9eeb-3facce3b0b1f.png)

**Comment by mreekie** [comment]
Drew removed the CD tests and the app successfully deployed.

**Comment by mreekie** [comment]
DianaL — Today at 12:20 PM
@Drew @mick Looking at the registration page. See the error we saw last night at the end of the meeting. I see 
IntegrityError at /register/
NOT NULL constraint failed: account_profile.photo. I removed the photo it names here, so this tells me it's not updated with the newest code/database using postgres. That should resolve the issue as mentioned last night, hope that helps! Super close!

**Comment by mreekie** [comment]
Success! I made the single test that is run successful by making the path relative.
Let's try adding in the other unit tests that were created for TDD.

**Comment by mreekie** [comment]
[@dliu936 reported in](https://discord.com/channels/1008812300305702912/1035178215834128395/1046221612195774549) on the database side of things tonight.
@mick @Drew @Kelly All, good news regarding  #105: recreated the SQLite DB, errors are corrected and website is functioning via Digital Ocean, CI/CD pipeline is successfully pulling from Git (deployment not automatic though, maybe can work on that in the next sprint). I will update kanban this evening/tomorrow morning with appropriate documentation.

**Comment by dliu936** [comment]
We removed the test for now until we can further develop as part of a future story/sprint

**Comment by mreekie** [comment]
Ok. so we understand what the original problem is and it is fixed.
And we have a plan to address the db change triggered problem in the next sprint.
Closing this
