### ISSUE TITLE
[SIZE 4] [SPRINT 3] Impediment: CD fails after DB change

### ISSUE THREAD

**Issue by mreekie** [thisaintwork/AgileDungeonTrekking#109]
Description:
The app deployment is failing.  Using the logs and discussing the timeline,  we are fairly certain that:

Context:

This is related to the storing of photos in the database.  Support for this required the transition from Sqlite to postgres.  We have been having deployment issues since then.  There is a strong correlation between the change in the db technology and the issues

Our plan of attack:
- Any code/Database changes are rolled back to the working version
- Any settings changes are rolled back to the working version
- re-introduce changes to locate the break.

This is our starting point:

![image](https://user-images.githubusercontent.com/47538814/204684799-97656902-48a0-49e2-965e-e6fed1b3825c.png)

![2022-11-29_195421](https://user-images.githubusercontent.com/47538814/204684842-3f67216b-ab58-4116-b0e2-43e271907f49.png)

---

At the start of Sprint 3 we took another look at the size.
- We know now that we need to attach an external service to get postgres working.
- We have never done this before so this is going to take us some time.
- Sizing as a 4

**Comment by dliu936** [comment]
Moved to postgres; we found that SQLite was the issue

https://docs.google.com/document/d/1AuK-0lh0ny_xBkoEiHsIFhFARc-8frD1E42Sg-1D9Z8/edit

![Image](https://user-images.githubusercontent.com/54752285/205412969-c1bfe447-07bf-45bd-a787-2088df7874c7.png)
