### ISSUE TITLE
[1 POINTS] [SPRINT 3️⃣] As a player, I can create a race for my named character.

### ISSUE THREAD

**Issue by katja-doomslayer** [thisaintwork/AgileDungeonTrekking#111]
**User Story Title:** Character Race

**Opening & Details**
As a player, I can create a race for my named character. My choice of race establishes fundamental qualities that exist throughout my character’s adventuring career. The race of my character is important to share with the DM and other players so we can form a diverse team for our campaign.

**Success Criteria**
- [x] a player can choose one race for their character
- [x] selectable races are: Dragonborn, Dwarf, Elf, Gnome, Half-Elf, Halfling, Half-Orc, Human, and Tiefling

--- 

**Technical Tasks**

New field - character's Race

We are going to add these fields to:
- models.py
- forms.py
which already exist

We are making use of the dnd_character package which already supports these fields.

These things will make this a small and easy change.
Sizing at 1 point

**Def of done:**
- [x] Enable user to define up adding a character and then edit the new fields
- [x] The fields are visibile on the character dashboard page

**Comment by mreekie** [comment]
![Image](https://user-images.githubusercontent.com/47538814/207124644-a6eb83e6-48f6-43c3-a039-d84f45c544a2.png)
