### ISSUE TITLE
Sprint Planning: Stories are Sized Right

### ISSUE THREAD

**Issue by mreekie** [thisaintwork/AgileDungeonTrekking#46]
- [x] All of the stories in your sprint backlog are the right size: 
  - the size of each backlog item is less than half your forecast velocity for the sprint. 
- [x] If you noticed PBIs that are too large to get done in a sprint, you refined them by splitting them into smaller stories and estimating the smaller stories.
- [x] You decomposed user stories into developer tasks 

(2 points total)

**Comment by mreekie** [comment]
I asked for clarification here from Richard.
In my mental model
PBI - is anything on the backlog.
User story - A good PBI takes the form of a user story.
a "real user story"  - another way of saying that a user story is well formed. follows the rules of title, as a, I , so that I, and has acceptance criteria - and is well understood by everyone on the team.

Now suddenly he is talking about developer tasks as if they are different than a user story.
This breaks my whole world! :) 

Here is the [question to Richard](https://discord.com/channels/1008812300305702912/1010551699783557241/1037896679036289034)

**Comment by katja-doomslayer** [comment]
Move Issue #54 into the archive because it was split into smaller stories. Also make sure there are only 12 points in the sprint backlog!
