### ISSUE TITLE
[4 POINTS] As a DM or Player I can log into the website or create a new account.

### ISSUE THREAD

**Issue by mreekie** [thisaintwork/AgileDungeonTrekking#55]
**User Story Title: Accessible Website**

**Opening & Details:**
As a DM or player, I can access the "ADT" login page with a public URL. On the login page, I can login with an existing username/password combination or request an account by entering a unique user name and password. Both options will brin gme to the main page of the ADT site. Within 15 min of requesting an account, I will get a welcome email.

**Acceptance Criteria:**

- [ ] the username field accepts an email address of up to 30 characters
- [ ] Usernames must be a valid email addresses
- [ ] the password field accepts up to 30 characters
- [ ] A password must be at least eight characters long and  have at least one letter, one number, and one special character.
- [ ] a recognized username and password will bring the user to the main page
- [ ] a new username and password that meet the conditions will bring the user to the main page and send a welcome email to the new user.
- [ ] any condition violation during LOGIN will notify the user of the error and reprompt them to enter the correct username/password.
- [ ] any condition violation while requesting an account will notify the user of the error and reprompt them to enter a username/password which meets the necessary conditions.

**Story Points Estimate:** 4

**Definition of Ready**
- [x] User story has a title
- [x] User story opening sentence
- [x] User story additional details
- [x] User story has a clear, complete acceptance criteria
- [x] User story is estimated in story points
- [x] User story addresses a business need
- [x] User story has measurable acceptance criteria
- [x] User story is small enough for implementation in the given time, but large enough to provide customer value
- [x] Infrastructure and development tools are ready
- [x] User story meets the INVEST (Independent, Negotiable, Valuable, Estimable, Small & Testable) criteria

---
Was decomposed from Big Story: 
- #26 

Technical tasks:

**Description:**
We will create a functional login page that allows for a user to log in. If they don't have an account they will be able to create one.  They won't be able to do anything beyond that.  We will do basic client-side validation on the user input and handle basic errors and bad input gracefully.

The process will include a validation email that will be sent to the user within 15 minutes.

The login page will lead to the user's home page which for now will be a placeholder.

Definition of done:
- [x] landing page created
- [x] new user functionality implemented
- [x] existing user functionality implemented.
- [x] the username field accepts only a email address of up to 30 characters
- [x] the password field accepts passwords of 8 to 30 characters.
- [x] a password must have at least one letter, one number, and one special character.
- [x] A new user is able to complete the account creation process after receiving their validation email.
- [x] An existing user can successfully log in.
- [x] All unit tests pass

How to test:
- [x] Go to the test URL in a browser.
- [x] Verify that the page exists
- [x] Validate the look and feel with our product owner and real stakeholder

**Comment by katja-doomslayer** [comment]
Title: The ADT Website is accessible
**Opening & Details:**
As a DM or player, I can access the "ADT" login page with a public URL. On the login page, I can request an account by entering a unique user name and password. Within 15 min of requesting an account, I will get a welcome email.

Acceptance Criteria: 

- the username field accepts an email address of up to 30 characters
- Usernames must be a valid email addresses

- the password field accepts up to 30 characters
- A password must be at least eight characters long and  have at least one letter, one number, and one special character.

- a recognized username and password will bring the user to the main page
- a new username and password that meet the conditions will bring the user to the main page and send a welcome email to the new user.

- any condition violation during LOGIN will notify the user of the error and reprompt them to enter the correct username/password.
- any condition violation while requesting an account will notify the user of the error and reprompt them to enter a username/password which meets the necessary conditions.

**Comment by dhwcode** [comment]
**Developer Tasks** 
- format form for logging in
- setup Django DB for users

**Comment by mreekie** [comment]
Our stakeholder Lexi really liked the login page.
She gave us feedback that the font was too small.
She said that she may give us some additional custom DnD images in the future
