### ISSUE TITLE
[4 POINTS] Characters and Creatures.

### ISSUE THREAD

**Issue by mreekie** [thisaintwork/AgileDungeonTrekking#57]
**User Story Title:  Characters and Creatures.**

**Opening & Details:**
As a DM or player, once I have an account I can access characters and creatures from the dashboard. When I select "Characters", I see a list of the characters I have created and an option to create a new character. If I am creating my first character, the program immediately prompts me to enter my character's name. When I select creatures, I am brought to the creatures page or section.

**Acceptance Criteria:**

- [x] There is a page or section for Characters
- [x] There is a page or section for Creatures
- [x] The main ADT page links to the pages or sections for characters and creatures
- [x] Selecting the character link will return a page or section titled "Characters" 
- [x] If the user doesn't have a character, they can create one by clicking the "Create Character" button. 
- [x] If the user has already created a character, selecting "Characters" will display a list of active character(s) and an option to create an additional character.
- [x] Selecting creatures, will return a page or section titled "Creatures"

**Story Points Estimate:**

**Definition of Ready**
- [x] User story has a title
- [x] User story opening sentence
- [x] User story additional details
- [x] User story has a clear, complete acceptance criteria
- [x] User story is estimated in story points
- [x] User story addresses a business need
- [x] User story has measurable acceptance criteria
- [x] User story is small enough for implementation in the given time, but large enough to provide customer value

---
**Technical Tasks:**
- [x] Add character application to the web project
- [x] Define the URL routings
- [x] Create tests
- [x] Create html pages
- [x] Create models, forms, views 

---
Was decomposed from Big Story: 
- #26

**Comment by katja-doomslayer** [comment]
User Story for Issue https://github.com/thisaintwork/AgileDungeonTrekking/issues/57
Title: The "Agile Dungeon Trekking" website has three pages

Opening & Details:
Once I have an account, I can access characters, campaigns, or creatures from the primary ADT page. When I select character, the program prompts me to enter my character's name. When I select campaign, I can see a list of my active campaigns. When I select creatures, I am brought to the creatures sub-page.

Acceptance Criteria:
The main ADT page links to the sub-pages for characters, campaigns, and creatures
Selecting the character link will return a page titled "Characters" with a prompt the user to enter a character name. 
Selecting campaign will return a page titled 'Campaigns" with a list of all active campaigns
Selecting creatures, will return a page titled "Creatures"

**Comment by mreekie** [comment]
Notes for discussion of the technical tasks definition:
-  took a few minutes and broke out the description.
- Will continue later.
- 
![image](https://user-images.githubusercontent.com/47538814/202229327-ff510d6a-8095-4207-b725-df97e9d8663a.png)

**Comment by mreekie** [comment]
Working out the technical description.

**Comment by mreekie** [comment]
Using TDD for creatures page creation

**Comment by dliu936** [comment]
Completed tasks for characters page and start of creatures page in next spring; We need to refine creatures criteria for next sprint. 

-Switched to postgres SQL database due to the complexity of the model. This will impact CI/CD deployment

**Comment by dliu936** [comment]
Attaching documentation link of walk-through evidence of acceptance for this story. This is from a local database and may not match what is currently in the cloud. However, we can syncronize the two or a new user can build characters in the cloud once the site is up, as has been demonstrated locally here. Recommend the latter option.   

https://docs.google.com/document/d/1VcrI3M1l4KAXeir3y_HONhRB29AsJDPBYRuy2akJA3M/edit
