### ISSUE TITLE
[2 POINTS] [SPRINT 3️⃣] As a player I need a dashboard page where I can enter and edit information about my character(s).

### ISSUE THREAD

**Issue by katja-doomslayer** [thisaintwork/AgileDungeonTrekking#63]
**User Story Title: Character Sheets**

**Opening & Details:**
As a player, As a player, I want to store some basic information about my character so I can reference this information while I am playing. I need a dashboard page where I can enter and edit information about my character(s). Each character I create should have it's own dashboard.  I need to keep track of this information because as my level, hit points, ability scores and armor class increase my character gets more powerful.

**Acceptance Criteria:**
- [x] Each character has a unique dashboard
- [x] A user can edit any field and save the changes from the dashboard
- [x] The dashboard information persists between logins

---

Was decomposed from Big Story: 
- #26 

---
**Technical tasks:**
- Add fields to the database
- Create the supporting code
- create the accompanying html.

**Definition of Done:**
- [x] Ability to create a new character
- [x] Ability to edit a character
- [x] View the character on it's own dashboard page.
- [x] View all characters.

**Comment by mreekie** [comment]
![Image](https://user-images.githubusercontent.com/47538814/207119111-8467907a-3c5b-4b99-b4e7-8bb3f337e069.png)

**Comment by mreekie** [comment]
![Image](https://user-images.githubusercontent.com/47538814/207119192-3e4da18e-b764-413b-8e6c-9dac367239e8.png)

**Comment by mreekie** [comment]
Each character has a unique dashboard

![Image](https://user-images.githubusercontent.com/47538814/207119406-d1172662-f521-489f-9bcb-794db864fc02.png)

**Comment by mreekie** [comment]
![Image](https://user-images.githubusercontent.com/47538814/207119802-c832980d-3341-4e1a-8dd0-67f8c1373bf2.png)
