### ISSUE TITLE
[4 POINTS] [SPRINT 3] Character Name

### ISSUE THREAD

**Issue by katja-doomslayer** [thisaintwork/AgileDungeonTrekking#67]
**User Story Title:** Character Creation

**Opening & Details:**
As a player, I can create one or more characters on ADT so that I can reference this information while I am playing. I need to choose a unique name for my character. My name may reflect my backstory, my family, my race or my class. Character names are important to share with the DM and other players so we can roleplay as our characters during the campaign. 

**Acceptance Criteria:**
- [x] each player can create one named character
- [x] at least 10 independent characters can be created 
- [x] a character has a name of <= 30 characters.

---
Was decomposed from Big Story: 
- #26

**Comment by katja-doomslayer** [comment]
**PBI meets the Definition of Ready.**

- [ ] yes
- [ ] no

**Comment by mreekie** [comment]
sizing discussion:
- At 8 points this is going to be too large.
- We are going to break this into at least 2 pieces

**Comment by mreekie** [comment]
Very close to being done.
The images are in the database but not showing on the page

**Comment by mreekie** [comment]
![Image](https://user-images.githubusercontent.com/47538814/207075074-34d7cfaf-cbf3-47f8-962e-7762f8f6faa4.png)
