### ISSUE TITLE
[1 POINTS] [SPRINT 3️⃣] As a player I want to be able to add and change my Character level

### ISSUE THREAD

**Issue by katja-doomslayer** [thisaintwork/AgileDungeonTrekking#71]
Depends on:
- #63 
 
**User Story Title: Character Level**

**Opening & Details:**
As a player, I want to store some basic information about my character so I can reference this information while I am playing. Each character already has a has a unique name, race, and class. The next most important item is the character's level. I need this information so I know which abilities, attacks, spells and feats are available to my character. My character's level will change over the course of my character's campaign.

**Acceptance Criteria:**

- [x] a character has a  level between 1 and 20
- [x] a new character begins at level 1
- [x] a player can edit their character's level at any time

---
Was decomposed from Big Story: 
- #26 
---

**Technical Tasks**

New field - character's level  "Level"

We are going to add these fields to:
- models.py
- forms.py
which already exist

We are making use of the dnd_character package which already supports these fields.

These things will make this a small and easy change.
Sizing at 1 point

**Def of done:**
- [x] Enable user to define up adding a character and then edit the new fields
- [x] The fields are visibile on the character dashboard page

**Comment by mreekie** [comment]
![Image](https://user-images.githubusercontent.com/47538814/207123048-4cfee6ce-145b-40e2-88ab-3d7408ed860e.png)



![Image](https://user-images.githubusercontent.com/47538814/207123067-fd93ea7b-9303-48ef-9077-d75a024a108e.png)



![Image](https://user-images.githubusercontent.com/47538814/207123139-c9ea0250-5037-4cf7-b6a8-b0f35cd2683d.png)
