### ISSUE TITLE
[4 POINTS] As a stakeholder, want to access an internal preview of the "ADT" login page so I can judge the look and feel

### ISSUE THREAD

**Issue by mreekie** [thisaintwork/AgileDungeonTrekking#89]
**Opening & Details:**
As a DM or player, I can access the "ADT" login page _from within our dev environment_. On the login page, there are fields for a user name and password. There are options to request a new account or to login to an existing account.  

I want to do this so that I can see something quickly and see if I like where it's going.

**Acceptance Criteria:**
- the opening page includes fields for a username and a password, 
- The opening page includes a radial button labeled "Request New Account" and a radial button labeled "Login" 
- Our user stakeholder has seen the page and has given us feedback on the look and feel.

**Estimate in Story Points:** in title

**Definition of Ready**
- [x] User story has a title
- [x] User story opening sentence
- [x] User story additional details
- [x] User story has a clear, complete acceptance criteria
- [x] User story is estimated in story points
- [x] User story addresses a business need
- [x] User story has measurable acceptance criteria
- [x] User story is small enough for implementation in the given time, but large enough to provide customer value
- [x] Infrastructure and development tools are ready
- [x] User story meets the INVEST (Independent, Negotiable, Valuable, Estimable, Small & Testable) criteria

Decomposed from Big Story: 
- #26 
---

Technical tasks:

**Description:**

We want to be able to get our product owner and our real stakeholder a look at what we're thinking of for the login page as soon as possible.   However this is our first sprint so we need to also get our dev and production environments sorted out.  If we concentrate on getting the dev environment sorted and get a first prototype of the login page completed, someone else can be sorting out the production environment where we will host our work. 

Definition of done:
- [x] setup Django environment
- [x] hook it in with GitHub
- [x] Create the Django framework
- [x] Create the web page
   - The opening page needs include include fields for a username and a password, 
   - The opening page needs include a radial button labeled "Request New Account"
   - The opening page needs include a radial button labeled "Login" 

How to test:
- [x] Go to the test URL in a browser.
- [x] Verify that the page exists
- [x] Validate the look and feel with our product owner and real stakeholder

**Comment by dliu936** [comment]
Landing page created with Django

**Comment by dliu936** [comment]
Used TDD including 11 unit tests as documented here: 

[Agile Dungeon Trekking TDD.docx](https://github.com/thisaintwork/AgileDungeonTrekking/files/9997640/Agile.Dungeon.Trekking.TDD.docx)
