### ISSUE TITLE
[2 POINTS] [SPRINT 3] Login Page Readability Improvement

### ISSUE THREAD

**Issue by katja-doomslayer** [thisaintwork/AgileDungeonTrekking#90]
**User Story Title:  Login Page Improvements.**

**Opening & Details:**
As a DM or player, I need to be able to read the text on the login page on my laptop so I can login when I am on vacation.  I have a small laptop for travel and it was too hard to read the text. 

**Acceptance Criteria:**
- [ ] Font size on the user dashboard is large enough to read on a 13" laptop screen by the average user (eye sight in range of 0 +/- 1 diopter)

**Story Points Estimate:**
[2 POINTS]

**Definition of Ready**
- [x] User story has a title
- [x] User story opening sentence
- [x] User story additional details
- [x] User story has a clear, complete acceptance criteria
- [x] User story is estimated in story points
- [x] User story addresses a business need
- [x] User story has measurable acceptance criteria
- [x] User story is small enough for implementation in the given time, but large enough to provide customer value
- [x] Infrastructure and development tools are ready
- [x] User story meets the INVEST (Independent, Negotiable, Valuable, Estimable, Small & Testable) criteria

---

Technical plan
- We will modify the default CSS file - probably the font-size attribute

**Comment by katja-doomslayer** [comment]
- [ ] Kelly will add stakeholder images to this ticket.

**Comment by mreekie** [comment]
This has bled over from Sprint 2.
Going into Sprint 3, no change.
It is in this sprint backlog

**Comment by mreekie** [comment]
pair programming notes:
- Modifying the bass.css to putting the change inline font-size tag directly in the dashboard.

**Comment by mreekie** [comment]
![image](https://user-images.githubusercontent.com/47538814/206940619-a2e62a00-0d10-4d2e-bd84-bf278bc92429.png)
