### ISSUE TITLE
[2 POINTS] Conduct testing earlier and more frequently

### ISSUE THREAD

**Issue by dhwcode** [thisaintwork/AgileDungeonTrekking#91]
**User Story Title:  Conduct testing earlier and more frequently.**

**Opening & Details:**
In an effort to incorporate what was learned from the Sprint Retrospective on November 10th, the Traveling Players created this backlog item to address TDD. 

**Acceptance Criteria:**
- [x] Initialize testing schedule in first Daily Scrum of Sprint
- [ ] Make plans for reporting test results in first Daily Scrum of Sprint

**Story Points Estimate:**

**Definition of Ready**
- [x] User story has a title
- [x] User story opening sentence
- [x] User story additional details
- [x] User story has a clear, complete acceptance criteria
- [x] User story is estimated in story points
- [x] User story addresses a business need
- [x] User story has measurable acceptance criteria
- [x] User story is small enough for implementation in the given time, but large enough to provide customer value
- [x] Infrastructure and development tools are ready
- [x] User story meets the INVEST (Independent, Negotiable, Valuable, Estimable, Small & Testable) criteria

---

**Comment by mreekie** [comment]
We made a plan to lead with testing this sprint and ensured that our dev was test first (i.e. TDD).
